services:
  nginx:
    container_name: exia
    build:
      context: ${NGINX}
      dockerfile: Dockerfile
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ${NGINX}/html:/var/www/html
      - ${NGINX}/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

  uvicorn:
    container_name: seven-swords
    build:
      context: ${UVICORN}
      dockerfile: Dockerfile
    volumes:
      - ${UVICORN}/app:/code/app
    networks:
      - default

  certbot:
    container_name: certbot
    image: certbot/certbot:v1.7.0
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ${NGINX}/html:/var/www/html
      - ${NGINX}/default.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    name: ${NETWORK}
